/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.sql.*;
import Entity.MainUser;
import howmuchwehave.Tolls;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Dictionary;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author YOUCEF
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGroup1 = new javax.swing.ButtonGroup();
        BtnGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DcDate = new com.toedter.calendar.JDateChooser();
        TxtPrice = new controls.JTextBox(30);
        TxtName = new controls.JTextBox(30);
        TxtLocation = new controls.JTextBox(30);
        BtnUpdate = new controls.JMyBoutton();
        BtnAdd = new controls.JMyBoutton();
        BtnFind = new controls.JMyBoutton();
        BtnDelete = new controls.JMyBoutton();
        BtnAll = new controls.JMyBoutton();
        jLabel5 = new javax.swing.JLabel();
        RdoPrice = new javax.swing.JRadioButton();
        RdoName = new javax.swing.JRadioButton();
        RdoLocation = new javax.swing.JRadioButton();
        RdoDate = new javax.swing.JRadioButton();
        BtnSearsh = new controls.JMyBoutton();
        TxtSearsh = new controls.JTextBox(30);
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        DcDate2 = new com.toedter.calendar.JDateChooser();
        TxtLocation2 = new controls.JTextBox(30);
        TxtName2 = new controls.JTextBox(30);
        TxtPrice2 = new controls.JTextBox(30);
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BtnAdd2 = new controls.JMyBoutton();
        BtnUpdate2 = new controls.JMyBoutton();
        BtnDelete2 = new controls.JMyBoutton();
        BtnFind2 = new controls.JMyBoutton();
        BtnAll2 = new controls.JMyBoutton();
        jLabel10 = new javax.swing.JLabel();
        RdoPrice2 = new javax.swing.JRadioButton();
        RdoName2 = new javax.swing.JRadioButton();
        RdoLocation2 = new javax.swing.JRadioButton();
        RdoDate2 = new javax.swing.JRadioButton();
        BtnSearch2 = new controls.JMyBoutton();
        TxtSearsh2 = new controls.JTextBox(30);
        BtnHMIPFA = new controls.JMyBoutton();
        BynHMIPFTM = new controls.JMyBoutton();
        BtnHMIPFA2 = new controls.JMyBoutton();
        BynHMIPFTM2 = new controls.JMyBoutton();
        BtnClear = new controls.JMyBoutton();
        BtnClear2 = new controls.JMyBoutton();
        TxtNumber = new controls.JTextBox(30);
        jLabel11 = new javax.swing.JLabel();
        TxtNumber2 = new controls.JTextBox(40);
        jLabel12 = new javax.swing.JLabel();
        jMyBoutton1 = new controls.JMyBoutton();
        jMyBoutton2 = new controls.JMyBoutton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number Of Operation", "Price", "Name", "Location", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Name :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Price  :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Date  :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Location :");

        BtnUpdate.setText("Update");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        BtnAdd.setText("Add");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        BtnFind.setText("Find");
        BtnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFindActionPerformed(evt);
            }
        });

        BtnDelete.setText("Delete");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        BtnAll.setText("All");
        BtnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Searsh By :");

        RdoPrice.setBackground(new java.awt.Color(255, 255, 255));
        RdoPrice.setSelected(true);
        RdoPrice.setText("Price");
        RdoPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdoPriceActionPerformed(evt);
            }
        });

        RdoName.setBackground(new java.awt.Color(255, 255, 255));
        RdoName.setText("Name");

        RdoLocation.setBackground(new java.awt.Color(255, 255, 255));
        RdoLocation.setText("Location");

        RdoDate.setBackground(new java.awt.Color(255, 255, 255));
        RdoDate.setText("Date");

        BtnSearsh.setText("Searsh");
        BtnSearsh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSearshActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number Of Operation", "Price", "Name", "Location", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Date  :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Location :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Name :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Price  :");

        BtnAdd2.setText("Add");
        BtnAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdd2ActionPerformed(evt);
            }
        });

        BtnUpdate2.setText("Update");
        BtnUpdate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdate2ActionPerformed(evt);
            }
        });

        BtnDelete2.setText("Delete");
        BtnDelete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDelete2ActionPerformed(evt);
            }
        });

        BtnFind2.setText("Find");
        BtnFind2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFind2ActionPerformed(evt);
            }
        });

        BtnAll2.setText("All");
        BtnAll2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAll2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Searsh By :");

        RdoPrice2.setBackground(new java.awt.Color(255, 255, 255));
        RdoPrice2.setSelected(true);
        RdoPrice2.setText("Price");

        RdoName2.setBackground(new java.awt.Color(255, 255, 255));
        RdoName2.setText("Name");

        RdoLocation2.setBackground(new java.awt.Color(255, 255, 255));
        RdoLocation2.setText("Location");

        RdoDate2.setBackground(new java.awt.Color(255, 255, 255));
        RdoDate2.setText("Date");

        BtnSearch2.setText("Searsh");
        BtnSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSearch2ActionPerformed(evt);
            }
        });

        BtnHMIPFA.setText("How Much I Pay For This Mouth");
        BtnHMIPFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHMIPFAActionPerformed(evt);
            }
        });

        BynHMIPFTM.setText("How Much I Pay For All To Now");
        BynHMIPFTM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BynHMIPFTMActionPerformed(evt);
            }
        });

        BtnHMIPFA2.setText("How Much I Made For All To Now");
        BtnHMIPFA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHMIPFA2ActionPerformed(evt);
            }
        });

        BynHMIPFTM2.setText("How Much I Made Form This Mouth");
        BynHMIPFTM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BynHMIPFTM2ActionPerformed(evt);
            }
        });

        BtnClear.setText("C");
        BtnClear.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });

        BtnClear2.setText("C");
        BtnClear2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        BtnClear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClear2ActionPerformed(evt);
            }
        });

        TxtNumber.setEditable(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Number");

        TxtNumber2.setEditable(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Number :");

        jMyBoutton1.setText("NOW");
        jMyBoutton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jMyBoutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyBoutton1ActionPerformed(evt);
            }
        });

        jMyBoutton2.setText("EXIT");
        jMyBoutton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jMyBoutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyBoutton2ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setText("Management My Money");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(DcDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TxtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnAll, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtName2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtLocation2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(DcDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jMyBoutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RdoPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RdoName, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RdoLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TxtSearsh, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RdoDate, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnSearsh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BynHMIPFTM, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnHMIPFA, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtSearsh2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RdoPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RdoName2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RdoLocation2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RdoDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(BynHMIPFTM2, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                .addComponent(BtnHMIPFA2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(338, 338, 338)
                            .addComponent(BtnClear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jMyBoutton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnUpdate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnDelete2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnFind2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnAll2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(381, 381, 381))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(TxtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(TxtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(TxtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(DcDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnUpdate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnDelete2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnFind2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnAll2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(RdoLocation)
                            .addComponent(RdoDate)
                            .addComponent(RdoPrice)
                            .addComponent(RdoName))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnSearsh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtSearsh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnHMIPFA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BynHMIPFTM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(RdoLocation2)
                            .addComponent(RdoDate2)
                            .addComponent(RdoPrice2)
                            .addComponent(RdoName2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtSearsh2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(TxtLocation2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DcDate2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BynHMIPFTM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnHMIPFA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnClear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMyBoutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMyBoutton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        db.go.fillToJTable("mainuser2", jTable2);
        db.go.fillToJTable("mainuser", jTable1);
        TxtNumber2.setText(m.getAutoNumber2());
        TxtNumber.setText(m.getAutoNumber());
        BtnAdd.setEnabled(true);
        BtnUpdate.setEnabled(false);
        BtnDelete.setEnabled(false);
        BtnAdd2.setEnabled(true);
        BtnUpdate2.setEnabled(false);
        BtnDelete2.setEnabled(false);
        BtnGroup1.add(RdoDate);
        BtnGroup1.add(RdoLocation);
        BtnGroup1.add(RdoName);
        BtnGroup1.add(RdoPrice);
        BtnGroup2.add(RdoDate2);
        BtnGroup2.add(RdoLocation2);
        BtnGroup2.add(RdoName2);
        BtnGroup2.add(RdoPrice2);
    }//GEN-LAST:event_formWindowOpened
    private void setValues() {
        m.setNumber(Integer.parseInt(TxtNumber.getText()));
        m.setPrice(Double.parseDouble(TxtPrice.getText()));
        m.setName(TxtName.getText());
        m.setLocation(TxtLocation.getText());
        SimpleDateFormat d = new SimpleDateFormat("yyyy-MM-dd");
        m.setDate((d.format(DcDate.getDate())).toString());

    }

    private void setValues2() {
        m.setNumber2(Integer.parseInt(TxtNumber2.getText()));
        m.setPrice2(Double.parseDouble(TxtPrice2.getText()));
        m.setName2(TxtName2.getText());
        m.setLocation2(TxtLocation2.getText());
        SimpleDateFormat d = new SimpleDateFormat("yyyy-MM-dd");
        m.setDate2((d.format(DcDate2.getDate())).toString());

    }
    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed

        setValues();
        m.add();
        db.go.fillToJTable("mainuser", jTable1);
        BtnUpdate.setEnabled(false);
        BtnDelete.setEnabled(false);
        cleardata();
        TxtNumber.setText(m.getAutoNumber());
        //TxtNumber2.setText(m.getAutoNumber2());
        db.go.fillToJTable("mainuser", jTable1);
        //db.go.fillToJTable("mainuser2", jTable2);

    }//GEN-LAST:event_BtnAddActionPerformed

    private void BtnHMIPFA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHMIPFA2ActionPerformed
double r = 0;
       
        int n = jTable2.getRowCount();
        for(int x=0;x<n;x++){
        r+=Double.parseDouble(jTable2.getValueAt(x, 1).toString());
        }
        Tolls.MsgBox("ToTal = "+d.format(r)+" ZL");
    }//GEN-LAST:event_BtnHMIPFA2ActionPerformed

    private void BtnClear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClear2ActionPerformed
        cleardata2();
    }//GEN-LAST:event_BtnClear2ActionPerformed

    MainUser m = new MainUser();

    private void cleardata() {
        TxtSearsh.setText("");
        TxtName.setText("");
        TxtLocation.setText("");
        TxtPrice.setText("");
        TxtNumber.setText(m.getAutoNumber());
        DcDate.setDate(null);
        BtnAdd.setEnabled(true);
        BtnUpdate.setEnabled(false);
        BtnDelete.setEnabled(false);

    }

    private void cleardata2() {
        TxtSearsh2.setText("");
        TxtName2.setText("");
        TxtLocation2.setText("");
        TxtPrice2.setText("");
        TxtNumber2.setText(m.getAutoNumber2());
        DcDate2.setDate(null);
        BtnAdd2.setEnabled(true);
        BtnUpdate2.setEnabled(false);
        BtnDelete2.setEnabled(false);
    }
    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearActionPerformed
        cleardata();
    }//GEN-LAST:event_BtnClearActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        String n = m.getNameByValue(TxtNumber.getText());
        if (n.equals(TxtName.getText())) {
            if (Tolls.confirmMsg("Are you sure you want update ''" + TxtName.getText() + "'' ?")) {
                setValues();
                m.update();
                cleardata();
                db.go.fillToJTable("mainuser", jTable1);
            }
        } else {

            if (Tolls.confirmMsg("Are you sure you want update ''" + n + "'' to ''" + TxtName.getText() + "'' ?")) {
                setValues();
                m.update();
                cleardata();
                db.go.fillToJTable("mainuser", jTable1);
            }

        }

    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        if (Tolls.confirmMsg("Are you sure you want to delete ''" + TxtName.getText() + "'' ?")) {
            setValues();
            m.delete();
            cleardata();
            db.go.fillToJTable("mainuser", jTable1);
        }

    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void BtnAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdd2ActionPerformed

        setValues2();
        m.add2();
        db.go.fillToJTable("mainuser2", jTable2);
        BtnAdd2.setEnabled(true);
        BtnUpdate2.setEnabled(false);
        BtnDelete2.setEnabled(false);
        cleardata2();
        //TxtNumber.setText(m.getAutoNumber());
        TxtNumber2.setText(m.getAutoNumber2());
        //db.go.fillToJTable("mainuser", jTable1);
        db.go.fillToJTable("mainuser2", jTable2);
    }//GEN-LAST:event_BtnAdd2ActionPerformed

    private void BtnUpdate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdate2ActionPerformed
        String n = m.getNameByValue2(TxtNumber2.getText());
        if (n.equals(TxtName2.getText())) {
            if (Tolls.confirmMsg("Are you sure you want update ''" + TxtName2.getText() + "'' ?")) {
                setValues2();
                m.update2();
                cleardata2();
                db.go.fillToJTable("mainuser2", jTable2);

            }
        } else {
            if (Tolls.confirmMsg("Are you sure you want update ''" + n + "'' to ''" + TxtName2.getText() + "'' ?")) {
                setValues2();
                m.update2();
                cleardata2();
                db.go.fillToJTable("mainuser2", jTable2);

            }
        }
    }//GEN-LAST:event_BtnUpdate2ActionPerformed

    private void BtnDelete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDelete2ActionPerformed

        if (Tolls.confirmMsg("Are you sure you want to delete ''" + TxtName2.getText() + "'' ?")) {
            setValues2();
            m.delete2();
            cleardata2();
            db.go.fillToJTable("mainuser2", jTable2);
        }

    }//GEN-LAST:event_BtnDelete2ActionPerformed

    private void BtnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFindActionPerformed
        String str = Tolls.InputBox("Enter Number Of Opiration ... ").toString();
        db.go.fillToJTable("select * from mainuser where Number=" + Integer.parseInt(str), jTable1);
    }//GEN-LAST:event_BtnFindActionPerformed

    private void BtnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllActionPerformed
        db.go.fillToJTable("mainuser", jTable1);
    }//GEN-LAST:event_BtnAllActionPerformed

    private void BtnFind2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFind2ActionPerformed
        String str2 = Tolls.InputBox("Enter Number Of Opiration ... ").toString();
        db.go.fillToJTable("select * from mainuser2 where Number2=" + Integer.parseInt(str2), jTable2);        // TODO add your handling code here:
    }//GEN-LAST:event_BtnFind2ActionPerformed

    private void BtnAll2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAll2ActionPerformed
        db.go.fillToJTable("mainuser2", jTable2);

    }//GEN-LAST:event_BtnAll2ActionPerformed

    private void BynHMIPFTMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BynHMIPFTMActionPerformed
        double r = 0;
        int n = jTable1.getRowCount();
        for(int x=0;x<n;x++){
        r+=Double.parseDouble(jTable1.getValueAt(x, 1).toString());
        }
        Tolls.MsgBox("ToTal = "+d.format(r)+" ZL");
    }//GEN-LAST:event_BynHMIPFTMActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();

        try {
            TxtNumber.setText(jTable1.getValueAt(row, 0).toString());
            TxtPrice.setText(jTable1.getValueAt(row, 1).toString());

            TxtName.setText(jTable1.getValueAt(row, 2).toString());

            TxtLocation.setText(jTable1.getValueAt(row, 3).toString());
            SimpleDateFormat da = new SimpleDateFormat("yyyy-MM-dd");
            DcDate.setDate(da.parse(jTable1.getValueAt(row, 4).toString()));
        } catch (ParseException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        BtnAdd.setEnabled(false);
        BtnUpdate.setEnabled(true);
        BtnDelete.setEnabled(true);

    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int row = jTable2.getSelectedRow();
        TxtNumber2.setText(jTable2.getValueAt(row, 0).toString());
        TxtPrice2.setText(jTable2.getValueAt(row, 1).toString());
        TxtName2.setText(jTable2.getValueAt(row, 2).toString());
        TxtLocation2.setText(jTable2.getValueAt(row, 3).toString());
        SimpleDateFormat da = new SimpleDateFormat("yyyy-MM-dd");
        DcDate2.setDate(Date.valueOf(jTable2.getValueAt(row, 4).toString()));
        BtnAdd2.setEnabled(false);
        BtnUpdate2.setEnabled(true);
        BtnDelete2.setEnabled(true);


    }//GEN-LAST:event_jTable2MouseClicked

    private void RdoPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdoPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdoPriceActionPerformed

    private void BtnSearshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearshActionPerformed

        String strSelect = "select * from mainuser where ";

        if (RdoName.isSelected()) {
            strSelect += "Name like '%" + TxtSearsh.getText() + "%'";
            m.getCustomRows(strSelect, jTable1);
        } else if (RdoLocation.isSelected()) {
            strSelect += "Location like '%" + TxtSearsh.getText() + "%'";
            m.getCustomRows(strSelect, jTable1);
        } else if (RdoDate.isSelected()) {
            strSelect += "Date like '%" + TxtSearsh.getText() + "%'";
            m.getCustomRows(strSelect, jTable1);
        } else if (RdoPrice.isSelected()) {
            strSelect += "Price =" + TxtSearsh.getText();
            m.getCustomRows(strSelect, jTable1);

        }
        cleardata();
    }//GEN-LAST:event_BtnSearshActionPerformed

    private void BtnSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearch2ActionPerformed
        String strSelect = "select * from mainuser2 where ";
        if (RdoName2.isSelected()) {
            strSelect += "Name2 like '%" + TxtSearsh2.getText() + "%'";
            m.getCustomRows2(strSelect, jTable2);
        } else if (RdoLocation2.isSelected()) {
            strSelect += "Location2 like '%" + TxtSearsh2.getText() + "%'";
            m.getCustomRows2(strSelect, jTable2);
        } else if (RdoDate2.isSelected()) {
            strSelect += "Date2 like '%" + TxtSearsh2.getText() + "%'";
            m.getCustomRows2(strSelect, jTable2);
        } else if (RdoPrice2.isSelected()) {
            strSelect += "Price2 =" + TxtSearsh2.getText();
            m.getCustomRows2(strSelect, jTable2);

        }
        cleardata2();
    }//GEN-LAST:event_BtnSearch2ActionPerformed
DecimalFormat d = new DecimalFormat("0.00");
    private void BtnHMIPFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHMIPFAActionPerformed
        
        double r = 0;
        
        String StrSelect = "select * from mainuser where Date like '%"+Tolls.InputBox("Enter number of mouth in this form '' YYYY-MM '' ").toString()+"%'";
        m.getCustomRows(StrSelect, jTable1);
        int n = jTable1.getRowCount();
        for(int x=0;x<n;x++){
        r+=Double.parseDouble(jTable1.getValueAt(x, 1).toString());
        }
        Tolls.MsgBox("ToTal = "+d.format(r) +" ZL");
                db.go.fillToJTable("mainuser", jTable1);
        
        
    }//GEN-LAST:event_BtnHMIPFAActionPerformed

    private void BynHMIPFTM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BynHMIPFTM2ActionPerformed
  
        double r = 0;
        
        String StrSelect = "select * from mainuser2 where Date2 like '%"+Tolls.InputBox("Enter number of mouth in this form '' YYYY-MM '' ").toString()+"%'";
        m.getCustomRows2(StrSelect, jTable2);
        int n = jTable2.getRowCount();
        for(int x=0;x<n;x++){
        r+=Double.parseDouble(jTable2.getValueAt(x, 1).toString());
        }
        Tolls.MsgBox("ToTal = "+d.format(r)+" ZL");
                db.go.fillToJTable("mainuser2", jTable2);
    }//GEN-LAST:event_BynHMIPFTM2ActionPerformed

    private void jMyBoutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyBoutton2ActionPerformed
    
        if (Tolls.confirmMsg("DO YOU REALLY WANT TO EXIT :( ?")){
            System.exit(0);
    }
    }//GEN-LAST:event_jMyBoutton2ActionPerformed

    private void jMyBoutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyBoutton1ActionPerformed
        
        double r2= 0 ;
        double r = 0;
        int n = jTable1.getRowCount();
        for(int x=0;x<n;x++){
        r +=Double.parseDouble(jTable1.getValueAt(x, 1).toString());
        }
        
        int n2 = jTable2.getRowCount();
        for(int x=0;x<n2;x++){
        r2 +=Double.parseDouble(jTable2.getValueAt(x, 1).toString());
        }
        Tolls.MsgBox("ToTal = "+d.format(r2-r)+" ZL");
        
        
        
    }//GEN-LAST:event_jMyBoutton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMyBoutton BtnAdd;
    private controls.JMyBoutton BtnAdd2;
    private controls.JMyBoutton BtnAll;
    private controls.JMyBoutton BtnAll2;
    private controls.JMyBoutton BtnClear;
    private controls.JMyBoutton BtnClear2;
    private controls.JMyBoutton BtnDelete;
    private controls.JMyBoutton BtnDelete2;
    private controls.JMyBoutton BtnFind;
    private controls.JMyBoutton BtnFind2;
    private javax.swing.ButtonGroup BtnGroup1;
    private javax.swing.ButtonGroup BtnGroup2;
    private controls.JMyBoutton BtnHMIPFA;
    private controls.JMyBoutton BtnHMIPFA2;
    private controls.JMyBoutton BtnSearch2;
    private controls.JMyBoutton BtnSearsh;
    private controls.JMyBoutton BtnUpdate;
    private controls.JMyBoutton BtnUpdate2;
    private controls.JMyBoutton BynHMIPFTM;
    private controls.JMyBoutton BynHMIPFTM2;
    private com.toedter.calendar.JDateChooser DcDate;
    private com.toedter.calendar.JDateChooser DcDate2;
    private javax.swing.JRadioButton RdoDate;
    private javax.swing.JRadioButton RdoDate2;
    private javax.swing.JRadioButton RdoLocation;
    private javax.swing.JRadioButton RdoLocation2;
    private javax.swing.JRadioButton RdoName;
    private javax.swing.JRadioButton RdoName2;
    private javax.swing.JRadioButton RdoPrice;
    private javax.swing.JRadioButton RdoPrice2;
    private javax.swing.JTextField TxtLocation;
    private javax.swing.JTextField TxtLocation2;
    private javax.swing.JTextField TxtName;
    private javax.swing.JTextField TxtName2;
    private javax.swing.JTextField TxtNumber;
    private javax.swing.JTextField TxtNumber2;
    private javax.swing.JTextField TxtPrice;
    private javax.swing.JTextField TxtPrice2;
    private javax.swing.JTextField TxtSearsh;
    private javax.swing.JTextField TxtSearsh2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private controls.JMyBoutton jMyBoutton1;
    private controls.JMyBoutton jMyBoutton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
